model_settings:
  batch_size: 64
  epochs: 100
  lr: 0.1
  decay: 0.009
  embedding_dim: 100
  hidden_dim: 100
  train_sample_frac: 0.75
  valid_sample_frac: 0.25
  test_sample_frac: 1
  checkpoint_dir: "checkpoints"